= arrangeTable

== api使用

[source, javascript]
//----
    var itemData;
	var arrangeTable = new arrangeTable($(".arrangeTable"), {
		dataList: itemData, // <1>
		renderer: function(data, i){ // <2>
			return $('<li>').addClass('item').attr({'id': data.id})
					.append($("<i class='list-ico'>").addClass(data.icon))
					.append($('<span>').text(data.text))
					.append($('<span class="DrM-closeBtn">').text('-')); // 关闭按钮都是用户自定义的,
		},
		onItemTap: function(data){ // <3>
			$('.DraggableMenutittle').text('app.navigate='+ data.url);
		},
		onDragEnd:function(){ // <4>
			$('.DraggableMenutittle').text('onDragEnd');
		},
		onClose:function(){ // <5>
			$('.DraggableMenutittle').text('onClose');
		},
		onEditing:function(){ // <6>
//			console.log('进入编辑模式')
		}
	});
//----
<1>
<2>
<3>
<4>
<5>
<6>


== 组件html与css的约定

格子item是一样大小的方格

关闭按钮必须有"DrM-closeBtn"的className

== 思考问题

=== 编辑状态

如何进入编辑状态, 怎样定义编辑状态?
编辑状态是用户可以进行item的删除.
当长按item与拖拽item没有超出其原本范围就判断是进入编辑状态.

=== item布局

如何浮动item::
 本组件的原本思维是先让文本append到html里, 获取items格子的文本位置, 再让items脱离文本流, 重新定位排队, 所以初始化比较耗性能
 这样的思路是有利于提供多尺寸的items, 但由于posAry没有相应的调整, 所以其实没有意义!
 现在的思路是先把items以绝对定位append到html里, 然后获取item的尺寸作为容器的列数和行数, 也作为posAry的参考, 这样就一次性的脱离文本流

=== 用户的事件操作:

操作的类型有:

. 点击item -> 跳转页面
. 长按item -> 进入编辑模式 -> 松开item -> item保留编辑状态
. 长按item -> 进入编辑模式 -> 松开item -> item保留编辑状态 -> 点击其他item -> 该item退出编辑模式
. 长按item -> 进入编辑模式 -> 拖拽item -> 没有重排其他item -> 松开item -> item保留编辑状态
. 长按item -> 进入编辑模式 -> 拖拽item -> 产生重排其他item -> 松开item -> item退出编辑状态
. 编辑状态可以点击关闭按钮, 删除改item

=== 选择怎样的布局

==== 模式1: 文本流拖拽

原理::
item以position:relative布局,
特点: 视觉与文本位置一致
事件::
获取位置:
点击对象所获取的位置是文本文本位置, 也就是视觉位置
拖拽::
克隆item并插入到最后文本位置, 设css定位到原位, 动画效果技术: translate3D和transition
排序::
基于文本位置, 使用before方法插入就可以, 各item的文本位置自动更新
删除item:
删除后, 各item的文本位置自动更新

==== 模式2: 浮动拖拽

原理::
全部item以position:absolute且靠左上角, 排列布局使用translate3D改变xy轴是各个item有自己位置
特点:: 视觉位置与文本位置脱离关系
事件::
获取位置:
点击对象所获取的位置是文本文本位置, 不能直接获取视觉位置
措施::
定义可排序的数组变量indexAry来模拟文本位置与模拟DOM结构变化, 反映视觉位置
拖拽::
克隆item(同时已经克隆了位置等属性), 动画效果技术: translate3D和transition
排序::
不排序DOM结构即文本位置, 只做视觉排序. 对indexAry进行排序, items按照indexAry来浮动定位在对应的视觉位置来做出"排位"效果
删除item::
删除后, 对indexAry进行处理(模拟文本流的删除item效果: 在indexAry里删除item序号, 然后对大于该序号的序号都减一), 这样就及时反映文本位置在视觉位置情况

== 心得:
. 多重兼容模式对于缺乏经验来说是挑战, 可能混乱了视线, 所以建议先做最优性能的, 最后才兼容
. 多缓存变量(原型变量), 多是不合理的
. 以触控点的文档坐标减去container的文档坐标, 来获取触控点相对于container的坐标是不准确的, 错误情况:缩放屏幕, 原因: 触控点与container的文档坐标获取原理不同??
. 设计过程, 分获取数据与渲染画面, 触发事件

 思考空间:
 uiTarget的缓存是保存currentGridIndex还是currentGridPos, 考虑到reorder只关心currentGridIndex与floatGridIndex, 但得益于gridPosAry, 可以以pos直接获取index, 或以index直接获取pos

. 重要修改

 拖动的单位不再以li为单位, 会以li里的内容wrap"div".addClass(li.class), 以这div为拖动的对象, 而且是基于position:relative的模式
这样就可以避免了复制模式, 也可以避免bug:container的尺寸变化, 有利于setCSS的三种模式的统一位置(不再担心降级方法的css({"left":??}))的特殊处理,
这是因为, 原来clone的情况, 必须要cloneItem先改变css的坐标位置, 这样使得setCSS的三种模式里translate是基于改变后的css坐标, 而降级方案还是基于原来未改变的css坐标
这样的话, animateslide的情况也可以
但这不能实现, 因为拖动的item不能有基础坐标参考点的变化, 不然就更加复杂了


== 优化历程

一开始我是以效果为主导来写组件, 组件挂靠在jQuery.prototype对象里.

=== 升阶历程
* 应该从使用者的角度触发去思考, 以提供什么api为开始
* 组件的不应该以效果为主导, 应该以逻辑为主导
* 一开始我选择了多种实现方式, position:relative与absolute都有做, 后来选择absolute, 完全清理relative, 理由是项目是移动端就不考虑低端浏览器
* 审查代码, 去掉多余的代码, 简洁 // 这一步其实每一步都有做
* 类, 已实例对象来使用, 提高代码复用性
* 变量命名, 更加的语义化, 私有变量使用下划线开头
* 思考设计错误:
    ** 拖拽的item应该就是原item, 不用复制副本作为拖拽的对象
* 减少变量, 能不用的变量尽量废除
    ** 统一touchItem, dragItem, reorderItem都为$target变量
    ** 研究status应用: 没有需要保留的状态, 使用$editingItem的有无表示isEditing
    ** 不使用ghostItem, 暂时没有需要
* 使用css3提供动画性能, 使用rAF来提供渲染性能
* css3的兼容问题, 我再写一个可以复用的cssProp组件来处理, 之后使用其的api来执行动画就好了
    ** cssProp在页面初始化时检测移动端的兼容前缀: touchstart, -webkit等等, 选择transform方法的兼容方法
    ** 取代本组件原方法_applyTransition/ _disableTransition/ _setPosition/ _setProps/ _page
* 解耦方法, 更好的阅读性
    ** 分离UiTarget作为一个方法集合, 用于负责items的定位, 重排, 获取视觉位置的方法集合
    ** 分离UiItems作为一个方法集合, 用于负责拖拽对象的拖拽定位, 放大, 归位等等的方法集合
* 使用新方法transitionEnd的方法

=== 优化的难点
* 更好的阅读性, 这是全过程都不断考虑的
* 方法的解耦, 逻辑与效果
    ** onTouchMove事件的方法负责ui数据收集
    ** processHandler方法关注的是逻辑
        *** 拖拽的权限, 检测
        *** 负责执行哪些内容,
            **** 拖拽
            **** 如何才是触发重排的逻辑计算
    ** 拖拽的样式操作归一个对象处理
    ** 重排的样式处理归一个对象处理
* 简化ui操作触发的事件执行的内容
* 动画效果的优化
    ** 绝对定位, 各个item的格子位置存放在缓存里, 方便定位
    ** css3
    ** rAF

== 改进空间:
 1. 兼容转屏
 2. 要对uiItems, uiTarget重新审查构想

